### ISSUE TITLE
Allow use of HW regardless of it's use elsewhere

### ISSUE THREAD

**Issue by Nalum** [Berry-Pool/nami-wallet#115]
I have my hardware wallet setup in multiple places, can Nami allow this or what's the reason that you don't currently allow it?

The information box mentions preventing issues but what issues would be the reason behind this?

![Screenshot_20211202_113910](https://user-images.githubusercontent.com/384180/144417585-0fe0acf4-d034-40dd-8c42-29d2a67675f9.png)

![Screenshot_20211202_113930](https://user-images.githubusercontent.com/384180/144417965-faa301b2-9861-4643-a904-f1680c585328.png)

**Comment by pascallapointe** [comment]
Hi, Nami wallet do not support multiple addresses. You will notice that Daedalus create multiple address for a same wallet. This is a design choice to keep Nami fast, but it makes Daedalus to Nami incompatible. In fact, multiple addresses lost their upper hand (privacy & payment isolation) when Shelley & Mary with staking and transaction metadata were released. Privacy remain a possibility for unstaked wallet.

You can't use the same account in Nami and Daedalus. Nami use only 1 address and show only what is contained on that first address. Daedalus use a new one every transaction. You can fix it by consolidating your funds on the address displayed in Nami as the info box suggest. But using again that account with Daedalus will break it again.

Daedalus don't support multi-account, but Nami does, so you must use this isolation to prevent issue.

You have send the fund you wish to use with Nami on the account 2 of your ledger device. When connecting it to Nami, you are presented a choice of account to import, use the account 2 with Nami and send some funds to it.


Bellow some explanation:

A little information about how wallet accounts works. Your 24 seed is like a master key, other sub keys can be generated from it. The same for addresses. You can see this like a folder path on you filesystem, or a website URL. Picture it like this: /WalletMasterKey/{account-index-number}/{address-index-number}

So Nami use /WalletMasterKey/{account-index-number}/0, where you can use account index 0,1,2,3 etc. But the address is always the # 0

Daedalus use /WalletMasterKey/0/{address-index-number}, where you can use addresses index 0,1,2,3,etc. But the account is always the #0

When using Ledger Nano, the "WalletMasterKey" is inside the Ledger instead of on your computer, and the way you access account or addresses depends on what software (Daedalus or Nami) you use"

I hope this help everyone here to understand better how it works under the hood

**Comment by Nalum** [comment]
Thanks for the information, very helpful. Is it a case that you can only have one or the other?

So 1 account with many addresses or many accounts each with 1 address? Or can you have many accounts and many addresses for each account?

What is the rationale for limiting to 1 address? You mentioned privacy and payment isolation is there something that outlines why this is the case?

Thanks for your time, much appreciated 👍

**Comment by pascallapointe** [comment]
No you can have multiple accounts with multiple addresses, but using multiple addresses add extra processing, something we don't want. We actually only have to fetch the balance and history of 1 address. Otherwise the wallet need to checkup every addresses independently.

The rationale for limiting to 1 address is that the overhead of multiples addresses add no value.
The rationale for supporting multiples addresses don't exist anymore.

You can do some research about multiple address and privacy.

If we go back in 2019, there was no staking key attached to your wallet, and no possibility to attach metadata to a transaction.

Privacy with multiple address: in 2019 there was nothing tying addresses together, making it hard to tie all addresses to a single wallet. In was more private in the sense that it would have been hard for an external person to guess the balance of your wallet.
With staking, all addresses are linked to your staking key, so with one of your address I can find all other addresses of your wallet and therefore find out everything you ever made within that wallet.

Isolation: In 2019 there was no metadata. As an example, if many people send you a transaction, you had no way to tell what payment came from who and for purchasing what goods. Giving a different addresses for each purpose was fixing this.
With transaction metadata, there is better way to do things. You could attach "Order #28282 by Customer #123" to the transaction.

For theses reasons, multi-addresses are mostly things of the past and not a good design anymore since there is better way to do things now. And supporting them would slow down Nami Wallet and put an unnecessary stress on BlockFrost, which are kindly providing the data for free.

**Comment by Nalum** [comment]
Thank you very much for all the info, much appreciated :+1:

**Comment by Bookdat** [comment]
What are the steps exactly to fix this my monkey brain doesnt understand.
I used daedlus with nami. dont do it again. nami only uses one address.  

Please and Thank you <3
