### ISSUE TITLE
Absurd transaction fees

### ISSUE THREAD

**Issue by DRAGOUMx** [Berry-Pool/nami-wallet#148]
Good afternoon, I have a doubt, what is the reason that Namiwallet charges rates of 0.49 ada?

**Comment by alessandrokonrad** [comment]
Fee is proportional to the transaction size. If you have a lot of tokens and UTxOs in your wallet fees could easily become that high when you want to send something. This is not Nami specific, but rather how Cardano works. Nami always calculates the minimum fee that is need to successfully submit the transaction.

**Comment by pascallapointe** [comment]
If I might add some more details, there is a minimal ADA amount a UTxO must contain.
There is case where the change is under the minimum amount of ~1ADA, the leftover will be burned as fees on the network. This happen when you are trying to send the complete balance.

Example: A wallet contain 5.9 ADA. The user wish to send 5ADA. The fees should be 0.17ADA, but since the left over of 0.73 isn't enough to create a new "change" UTxO, the fees to make the transaction possible will be 0.9ADA. At this point, the user can try to send 5.73ADA to avoid losing the change as fee, or send more funds to the wallet.

**Comment by DRAGOUMx** [comment]
Thanks for your help.
