### ISSUE TITLE
coinSelection.js returns change for native tokens tx-out, but not for fee and for --change-address

### ISSUE THREAD

**Issue by zarej** [Berry-Pool/nami-wallet#169]
At line https://github.com/Berry-Pool/nami-wallet/blob/a14d26928de553681aed35ae5b9c722aaab7e79c/src/lib/coinSelection.js#L292 you are checking if there is enough lovelace in change to cover tx-out with native tokens but should we also need to cover:
-  fee and 
- amount to send to change address which is a minimum of 1 ADA 

Could you please explain to me if I got it wrong?

**Comment by pascallapointe** [comment]
Hi,

this line apply only for the change, so the minimum of 1 Ada will be added if this condition pass.

You are right about the fee. Actually the CoinSelection doesn't know about the surrounding transaction. Until last month, we were checking if the maximum fee were covered in that condition as well. The coinselection is flawed with or without that condition. There's a edge case where it will fail in both situation. We removed the check since one of the 2 cases seems to occur more often than the other. This was more a hack than a proper solution.

I won't give the details here since it is a little complex to explain, but there are cases with low balance accounts where there is a uncovered gap with fees caused by included assets in change.

I'm actually looking to rewrite the coinselection to be able to account properly for the exact fees. This will require the coinselection to be moved inside the serialization library transaction builder. Emurgo are already working on this, but we will provide our own flavor.

**Comment by zarej** [comment]
Thank you very much for the clarification
