### ISSUE TITLE
UX improvements suggestions

### ISSUE THREAD

**Issue by SamGCURIOM** [Berry-Pool/nami-wallet#21]
Hi there!

So far I really like my experience with NAMI Wallet. I have observed 2 things that could make a better user experience. Here they are:

1. When you click outside the extension to copy an address or an ADA amount to transfer, the extension closes and you have to start over. Keeping the extension open permanently would greatly improve this.

2. Once we enter our password to spend, we have to manually click on "ok" to proceed with the sending. Allowing us to use "enter" to confirm the transaction would be great to make the experience even smoother.

Thanks a lot and let me know if I'm in the wrong place to leave this kind of feedback.

Sam

**Comment by alessandrokonrad** [comment]
Hey thanks for the feedback!

To 1: Unfortunately this is a design decisions by the browsers and I can't force to keep it open. An idea I may implement soon is to store the current state in the localStorage when the extension closes, so that you can continue from the that point again.

To 2: For extra security you need to click the button. At least this was my idea, but if more demand this feature I could add the "Enter" key as well to confirm👍

**Comment by SamGCURIOM** [comment]
Thank you for replying that fast!

I think the solution to #1 would resolve the issue as it would prevent from doing manual entry to avoid closing the extension window.

I understand the design decision for the #2. I personaly would like to be able to press enter, but let's see what others think :)

Thank you for this awesome work.
