### ISSUE TITLE
min_ada_required error

### ISSUE THREAD

**Issue by radflipper** [Berry-Pool/nami-wallet#226]
First of all you're a rockstar. As a weekend warrior just trying to grasp whats going on here I am so grateful for all the work you've put in and the whole ecosystem wouldn't be where it is without it!!

Trying to work through how creating a signing a tx by connecting to the Nami wallet works. The one I haven't figured out yet is that in coinSelection.js its using min_ada_required() from the wasm library and its passing a second parameter of false but the min_ada_required function I am seeing only takes two BigNum's 

If I remove the false the randomImprove succeeds.

Maybe I'm looking at this wrong or there's an update somewhere I've missed?

**Comment by pascallapointe** [comment]
Hi, the reason is that Nami use a custom fork of the serialization library available under Alessandro github account. If you go directly to the serialization repository and look to the main branch code, you'll notice that there is quite a few change since the last official release.

The min_ada calculation have change with the release of Alonzo and now take the parameter coins_per_utxo_word instead of min_utxo_value. Currently both parameters are set to the  coins_per_utxo_word value to be backward compatible I suppose.

You can build the main branch of the serialization lib to access the latest version, just know that some of it might be unstable. If using the released version, just adapting the code like you did should do the trick, but the resulting output might not be the exact same. In short, as long as it doesn't ask for less than what the protocol really require you'll be fine. 

I think the new calculation require less Ada per assets. (With some reserve, that need to be verified)

**Comment by radflipper** [comment]
Excellent thanks for the response. I see the one in his account, I'll switch to that and see if it helps, its not the only oddity I've run into so I'm sure it can't hurt to be using the same version.
