### ISSUE TITLE
Imported me my wallet with my seed phrase and lost all funds and nft assets

### ISSUE THREAD

**Issue by gholmesoutdoorsy** [Berry-Pool/nami-wallet#234]
I imported my wallet using my seed phrase. Instead a new address was generated and my previous address was replaced.  I now have lost my funds and my assets.  Also confirming that https://twitter.com/inusaitamahelp_/ is legit Nami support?

**Comment by pascallapointe** [comment]
Hi,

Check your seed again, make sure you have the right one and that every word is the exact same. I'm sure you did it many time already.

The same 24 words will always generate the exact same set or key. There is no way around, it's math. And the same address will always be derived from it, same for the sub-accounts.

Also make sure you didn't use a sub-account by misguard when you first created a wallet, check under the menu if there is something there. You'll could have ended up using the second account without knowing it since Nami always open on the last account used.

Try to find what could have happened, make sure there is not been a mixup with another seed. Try to remember if you had to start over again when you first created the wallet. Sometime the popup was closing while entering the words and you had to do it again from the start, ending up with 2 recorded seed the same day. (Just an example, i'm not supposing anything)

And no, this twitter account is not from us, it's funny that it have more follower than me though..!

**Comment by gholmesoutdoorsy** [comment]
Closing this issue. It's been resolved. That user is out here replying to people sending comments on twitter and is scamming people out of crypto
