### ISSUE TITLE
Transaction Failed

### ISSUE THREAD

**Issue by Besnft** [Berry-Pool/nami-wallet#265]
I have been unable to send ADA from either of my 2 Nami wallets for the past 2 days straight. I have attempted about 10/15 transactions and none have been successful

**Comment by pascallapointe** [comment]
There is actually to much activity going on and Nami backend provider mempool is saturated. A mempool is like a queue where your transaction is waiting to get pushed to the blockchain.

Read this twitter chain post to learn more on what's going on: https://twitter.com/berry_ales/status/1483936557954486272

Try another wallet to send transaction, they are all relying on different server to communicate with the blockchain, they might not all be full. With Daedalus you have your own "waiting queue", but it's more heavy to run.

Also, if you have a transaction that is waiting to be pushed to the blockchain, all subsequent transaction attempt will fail since your wallet UTxO are already "engage" and the change as not been returned yet.

**Comment by Besnft** [comment]
Hi,

This is a terrible response honestly.

Use another wallet, really?

I guess i’ll have to send everything from my nami and use another wallet
forever. Sick of dealing with nami.

**Comment by pascallapointe** [comment]
I'm only trying to help here.
There is reason why this is happening, and reason why having too many people trying to use the same wallet at the same time is giving this result.

Please take the time to read this other twitter post to learn more on this: https://twitter.com/berry_ales/status/1485198340698562563?s=20

I just explained you in my first response why you would not experience the same waiting on Daedalus than on a light wallet.

Also, keep in mind that this is a free project, user are not paying for using it. Adding more server to support Nami doesn't make sense from a business point of view. We are already more than lucky to have such a great support from Blockfrost.
