### ISSUE TITLE
Missing ADA

### ISSUE THREAD

**Issue by Dineen94** [Berry-Pool/nami-wallet#282]
Hi guys,

Please can you help me with an issue on Nami? It appears in my wallet that i have 301 ADA in my wallet when I should have 3191 ADA.

In transaction ID 30fb2777a6816566798628992441e5a26c68ab92f1e69e62f865fb480dbafaf8, I sent 2000 ADA to my other sub-wallet in Nami but it appears that another 2869 ADA has gone. It shows in my "http://pool.pm" that the ADA is still in my wallet but I am unable to see it in Nami?
(https://pool.pm/addr1q9szxdf0neuz8zvhsxyuuyj63r4y08jvfwtph57a937l2s7meczvtpxskk3hg2ra8r3ak546g2rc3gfa0xqhe03fl9hsk65m9g)
 
Please help :)

**Comment by HeptaSean** [comment]
You probably have done transactions with another wallet app than Nami.

All other wallet apps use a lot of addresses per wallet, while Nami only sees and uses the first one. Transactions in other wallet apps move things away from where Nami can see them. But it should show the real balance in a pop-up at the small “i” next to the balance.

You can move everything back to that first address (the one Nami shows in “Receive”) with a transaction in the other wallet app.

ccvault has a “Single address mode” in the settings to prevent this moving away and cooperate nicely with Nami.

(Also try “Collateral” on the same page if you set a collateral in Nami. But do not set it in ccvault. ccvault will recognise the collateral UTxO done by Nami, but Nami will not if ccvault does it. Both knowing it should prevent ccvault from using the collateral UTxO for normal transactions. Otherwise, Nami would prompt to set it again and again costing transaction fees.)

**Comment by Dineen94** [comment]
Yes! this sorted it, sent all ADA to my OG address and it's fixed, thank you!
________________________________

**Comment by HeptaSean** [comment]
That's good to hear!

Would you close the issue, so that the Nami developers have less to go through, when they return here?
