### ISSUE TITLE
Error message about balance after CCvault import and stuck listings on JPG

### ISSUE THREAD

**Issue by ghostbear33** [Berry-Pool/nami-wallet#286]
Hey I was wondering if I could get some help with an error message I keep getting. To get access to my ADA that was frozen in Nami, I restored my wallet in ccvault using my seed phrase and now I keep getting an error message in all of my Nami accounts that are connected about my balance. I tried following the instructions in the error message but nothing has worked. I have listings on JPG that I can't take down even when I send ADA to provide collateral. I successfully add collateral but then it keeps telling me I don't have any so my tokens are just stuck. I'm okay with leaving them listed as long as people are able to purchase them but I'm concerned the error in my wallet is preventing that.

Thanks for any help you can provide

**Comment by luisaaagam** [comment]
similar to my issue #283 , would hope to get a resolution from the team!

**Comment by HeptaSean** [comment]
Nami just sees and uses the first address of your wallet, while ccvault and all the others generate new addresses all the time. Therefore, the other wallets move things away from, where Nami can see them, with every transaction.

ccvault has a “Single address mode” in the settings to prevent that and cooperate nicely with Nami.

Perhaps, you have to move everything back to that first address in a single transaction done in ccvault.

(Also try “Collateral” on the same page if you set a collateral in Nami. But do not set it in ccvault. ccvault will recognise the collateral UTxO done by Nami, but Nami will not if ccvault does it. Both knowing it should prevent ccvault from using the collateral UTxO for normal transactions. Otherwise, Nami would prompt to set it again and again costing transaction fees.)

**Comment by ghostbear33** [comment]
> Nami just sees and uses the first address of your wallet, while ccvault and all the others generate new addresses all the time. Therefore, the other wallets move things away from, where Nami can see them, with every transaction.
> 
> ccvault has a “Single address mode” in the settings to prevent that and cooperate nicely with Nami.
> 
> Perhaps, you have to move everything back to that first address in a single transaction done in ccvault.
> 
> (Also try “Collateral” on the same page if you set a collateral in Nami. But do not set it in ccvault. ccvault will recognise the collateral UTxO done by Nami, but Nami will not if ccvault does it. Both knowing it should prevent ccvault from using the collateral UTxO for normal transactions. Otherwise, Nami would prompt to set it again and again costing transaction fees.)

That worked! Thank you!
