### ISSUE TITLE
After i add Nami wallet in ccvault i had this issue

### ISSUE THREAD

**Issue by burnerscy** [Berry-Pool/nami-wallet#295]
We have detected that the current wallet seed has been used with another wallet.

Real balance

60.031662 ₳
To remove this warning and prevent any issue using Nami Wallet, consider the following options:

Internal transfer of your complete balance from your usual wallet to your Nami Wallet receive address.
Creating a brand new wallet that will be used only with this wallet.

**Comment by HeptaSean** [comment]
Nami just sees and uses the first address of your wallet, while ccvault and all the others generate new addresses all the time. Therefore, the other wallets move things away from where Nami can see them with every transaction.

ccvault has a “Single address mode” in the settings to prevent that and cooperate nicely with Nami.

Probably, you have to move everything back to that first address in a single transaction done in ccvault as Nami tells you.

(Also try “Collateral” on the same page if you set a collateral in Nami. But do not set the collateral in ccvault! ccvault will recognise the collateral UTxO done by Nami, but Nami will not recognise if ccvault does it. Both knowing the collateral UTxO should prevent ccvault from using it for normal transactions. Otherwise, Nami would prompt to set it again and again costing transaction fees.)

**Comment by burnerscy** [comment]
thank you very much. that fixed the issue

**Comment by HeptaSean** [comment]
That's good!

Would you close the issue, so the Nami developers have less to do, when they finally come to going through all this?
