### ISSUE TITLE
I can't see the pavia token. 아이 캔트 시 더 페이비어 토우컨.

### ISSUE THREAD

**Issue by chaehunyun** [Berry-Pool/nami-wallet#300]
After depositing Ada in Nami wallet, I swapped with Pavia in Sundaeswap, and the swap became normal, but the Pavia token was not displayed.
Even if you add tokens, they can't be added and there's no indication.Only ada was displayed and the ada disappeared as much as the swapped.
Help me.
3783c9b1b6054219acf378f3af7cc8ba51d113d434051c51fa0c9178aba5549e

**Comment by HeptaSean** [comment]
On SundaeSwap, is the order open or does it say completed?

Your wallet: https://cardanoscan.io/address/addr1qxajmmrps5w3hen0wzfnh4z5rdc40apmyhzgqq65uqvjyw9anp7trcxu7ns2c8pll5nfyyyfcuqarkskcd7mxvge2zys3zptkt
It shows only the orders/swap requests going out, but no completion of the swap coming in, so there are no Pavia that can be shown to you.

It is possible that the order was completed, but was not sent out by SundaeSwap up to now.

Or it was not completed, cannot be completed now, because the price is already to high. In that case, you can also cancel the order (in the SundaeSwap interface) to get your ADA back.

**Comment by HeptaSean** [comment]
According to https://cardanoscan.io/address/addr1qxajmmrps5w3hen0wzfnh4z5rdc40apmyhzgqq65uqvjyw9anp7trcxu7ns2c8pll5nfyyyfcuqarkskcd7mxvge2zys3zptkt, you have now successfully cancelled the 1000 ADA order and received PAVIA for the other order.

Is there still an issue?

If not, it would be kind to close the three issues you opened.

**Comment by chaehunyun** [comment]
Yes, I think it went well.Thank you for your kind reply.
How do I close the inquiry I asked?

2022년 1월 24일 (월) 오후 6:30, Benjamin Braatz ***@***.***>님이 작성:

**Comment by HeptaSean** [comment]
If you go into the web interface (where you opened the issues), there is a “Close issue” button at the bottom (if you are logged in).

Your issues were:
https://github.com/Berry-Pool/nami-wallet/issues/299
https://github.com/Berry-Pool/nami-wallet/issues/300
https://github.com/Berry-Pool/nami-wallet/issues/301

Thank you!
