### ISSUE TITLE
Balance displaying wrong amount

### ISSUE THREAD

**Issue by pascallapointe** [Berry-Pool/nami-wallet#35]
Balance has be reporting showing wrong amount a few time by different user.

Example:

Balance showing 1.5 ADA

History (DESC order):

+1.5 ADA
+ 50 ADA

So here the transaction of 50ADA isn't reflected in the balance.
The last transaction is 1.5ADA and it is the only amount showing.
The balance hasn't updated fully on the last transaction, so the code need to be reviewed first to pin point the exact situation that could cause this to happen.

The user reported being able to transfer back the full balance to another wallet.

**Comment by pascallapointe** [comment]
There is a condition that prevent the balance from being updated if no new transactions have occurred.

You can see the condition in [index.js line 931](https://github.com/Berry-Pool/nami-wallet/blob/fa87bbd8410894193f902bd20241adb4ac129cf3/src/api/extension/index.js#L931)

My assumption is that the condition is only there to avoid unnecessary balance update.
@alessandrokonrad can you confirm that this is not there to prevent any issue?

To avoid the balance in storage from going out of sync, I would propose to either remove completely the condition, or find a way to force update at least on wallet opening and account switch.

**Comment by alessandrokonrad** [comment]
https://github.com/Berry-Pool/nami-wallet/blob/111e62a60416aee09ece0a5b89b094befb29dbf6/src/api/extension/index.js#L911-L924

The issue occurs because the new txHash was fetched correctly, which triggeres an update, but then the updateBalance function returns a blockfrost error for some reason (maybe because of high usage, nothing we can do about on our side).
So the way to fix it and to make sure all updates occur after a new txHash was found is to run an interval until the the new balance was actually fetched.
