### ISSUE TITLE
revamp api

### ISSUE THREAD

**Issue by xocdr** [Berry-Pool/nami-wallet#43]
Hi

some constructive feedback:

if you want MASS adaption of you wallet, then get rid of the cardano types.

Make the api as simple as possible: when sending a value send it as 12345.6789 ADA and not as a Value object.

When you send an address, send it as a bech32 address. Accept values in that format and transform your self.

Heck, you could have a raw api (with cardano types) and a default API with simple types.

One of the things that makes metamask and web3 so wonderful, is how easy it is to work with it. If you give this simplicity to web developers, you will be the standard wallet. Try to design APIs with your end user in mind, not the system you are interfacing with.

You can get in touch with me on discord if you want to discuss Anixai#4159. 

PS:  for the rest I am sending you a lot of LOVE for creating nami wallet. Thanks for all your efforts! If you want help / contributers, let me know.

Jeroen

**Comment by xocdr** [comment]
(and maybe have a small npm lib that can be used in the backend for instance as well, to verify signed data etc)

**Comment by alessandrokonrad** [comment]
Yes I totally understand that, but it is intended to be this way right now. There is a standard I follow:
https://github.com/cardano-foundation/CIPs/pull/88
The types are part of the ledger specs, which makes the API very flexible. A top level API simply solves this problem and yes that's the plan, which makes this pretty much like web3 then. But at the moment I don't have the time to build it.

**Comment by alessandrokonrad** [comment]
Without Alonzo and smart contracts, there is no reason to focus on a top level API at this stage.

**Comment by rooooooooob** [comment]
@xocdr as @alessandrokonrad  mentioned it is following the standard as specified in [CIP-30](https://github.com/cardano-foundation/CIPs/pull/88). The CIP is still a draft so if you have any comments about that they are best left there instead of in an individual wallet's repo. It is much better to have a single standard for communication with dApps instead of having a bunch of different wallets having different APIs, effectively either a) locking dApps to specific wallets (bad for users) or b) multiplying the work for dApp devs if they have to implement against multiple different APIs. (bad for devs)

Also keep in mind that as of the Mary hardfork with NFTs you can't just use a single number/string/whatever as you must support multiassets too, which can contain multiple in the same output. One issue with accepting this is that you would then have an inconsistency between parameters and return values since return values would have to always return the proper full `cbor<value>` type (or some other type capable of expressing multiassets). Concerning the bech32 addresses instead of cbor-encoded, there is already a comment in that CIP's PR about that asking if it should be changed to bech32 instead of cbor. It was cbor for consistency with the rest of the API. A type-choice between the two e.g. `cbor<address> | string` or `cbor<value> | string` could be possible, but you should post those suggestions in that CIP's PR to get the community's feedback.  However, as cbor is the standard across the cardano ecosystem and the fact that in order to use the other endpoints that require things like `cbor<transaction>` you likely would have access to the ability to easily (de)serialize simpler types like `value` or `address` in order to create those other types anyway.

If you want simple development that doesn't take into account multiassets or anything else like that then it's possible to write a wrapper library used *from within the dApp* that wraps these calls and then calls the corresponding API calls against the wallet's injected code, but it should only be the wallet's responsibility to provide a *common standard* that *all* dApps can interface with. Such a library could also provide additional utility functionality but this should not be a part of the wallet as long as the wallet provides access to the data required to implement that functionality. For example, web3 provides a tonne of extra functionality but requires a provider that has access to a full node (e.g. infura or self hosted node) to do so. This isn't really something that the wallet should need to be involved in (you must think about light wallets too) and can easily be a library that is part of the dApp instead.
