### ISSUE TITLE
How to fix INPUT_LIMIT_EXCEEDED (coin selection)

### ISSUE THREAD

**Issue by VNRG1993** [Berry-Pool/nami-wallet#515]
Hello,
I tried to buy an asset (339 Ada) on cnft.io and I got this error:

![image](https://user-images.githubusercontent.com/44643119/162631250-26b030f9-8781-43dc-bae6-79801efd703d.png)

Hopefully you guys can clarify and fix my problem asap before the asset will be gone which I was trying to buy.

Some more details:
- It was trying to buy via smart contract
- collateral was set
- I had enough coins to buy (368 Ada)

Ty in advance!

**Comment by pascallapointe** [comment]
You probably have this error because your wallet is composed of too many small UTxO, therefore, cnft.io isn't capable of building the transaction within the limit set in the coinselection algorithm.

ie: the limit of UTxO that can be included can be 20, but only no UTxO larger than 5ADA.

One thing you can try is to consolidate your UTxO set by sending to yourself a transaction as close as you can to the amount you are required to use. This will have for result to gather all small UTxO under a larger UTxO. So the next time the coinselection run, it will be able to match the buying price using less UTxOs.

**Comment by VNRG1993** [comment]
If I understood right:
Since I have 2 wallets, I can just transfer all coins from Nami to Daedalus.
Afterwards I transfer back to Nami with a similar amount as the asset pricing and this should fix this error.
Was that right? If yes, thank you very much for the fast reply and giving me more inside info about the system!

**Comment by pascallapointe** [comment]
In fact you can make a payment to yourself, that would save you one transaction.
Yes... it sound strange but you can send from you to you..!

So yes, if you know you did a lot of very small transactions/payment, this is probably the issue you are experiencing.

**Comment by VNRG1993** [comment]
Yeah, I have sold a lot of banked NFTs on CNFT.io where I earned 10 to 100 ada.
So everything makes sense now.

Closing this section now, so again, thank you very much!
